name: Xethya Test Runner

on:
  pull_request:
    branches:
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Use Yarn
      uses: Borales/actions-yarn@1.1.0
       
    - name: Install dependencies and test
      run: |
        yarn --frozen-lockfile
        yarn test
      env:
        CI: true
